# Generated by Django 5.0.1 on 2024-02-15 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_anime_list', '0003_anime_is_watched_anime_real_rating_anime_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anime',
            name='my_episode',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='anime',
            name='my_rating',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
