# Generated by Django 5.0.1 on 2024-02-15 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_anime_list', '0004_alter_anime_my_episode_alter_anime_my_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anime',
            name='real_rating',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
